### ISSUE TITLE
Неправильное поведение при пошаговом режиме Replay

### ISSUE THREAD

**Issue by aaaaaa2493** [moevm/adfmp18-poker#26]
Сделать так, чтобы фишки перемещались мгновенно в Pot при пошаговом режиме в паузе. Плавно при просмотре, и мгновенно при паузе

**Comment by freepower311** [comment]
Может, просто не вызывать методы анимации из core?

**Comment by aaaaaa2493** [comment]
Я и так не вызываю. Но это нужно проверить

**Comment by aaaaaa2493** [comment]
Вызывал, была ошибка в core
