### ISSUE TITLE
Проблема с передвижением Pot

### ISSUE THREAD

**Issue by aaaaaa2493** [moevm/adfmp18-poker#34]
Как воспроизвести:
1) Подождать пока все игроки сделают ход, начнётся перемещение
2) Во время перемещения нажать кнопку "Следующая рука"
3) Фишки продолжат двигаться, должны прекратить движение и исчезнуть

**Comment by freepower311** [comment]
Исправил, но пока не проверил

**Comment by aaaaaa2493** [comment]
Снова открыто, так как проблема появилась при переходе на анимацию встроенными средствами LibGDX.

**Comment by aaaaaa2493** [comment]
После решения этой задачи проверить, решилась ли задача #59

**Comment by aaaaaa2493** [comment]
С помощью точного клика у меня получилось сделать так, что уже началась следующая рука, блайнды поставились, и началось перемещение этих блайндов в пот

**Comment by freepower311** [comment]
Прерыватель действительно не работал. Кроме того я перенес вызов функции прерывания в core, чтобы не допустить рассинхронизацию вызовов.
