### ISSUE TITLE
Если есть анте, то блайнды и все ставки не отображаются 

### ISSUE THREAD

**Issue by aaaaaa2493** [moevm/adfmp18-poker#59]
Повторить:
1) запустить приложение
2) зайти в архив
3) найти в поиске bestest3
4) промотать до двух десяток у самого нижнего игрока с самыми крупными картами
5) В начале анте есть, а вот ставки игроков не отображаются

**Comment by freepower311** [comment]
Баг в ядре, мои функции не вызываются

**Comment by aaaaaa2493** [comment]
Да, в ядре
