### ISSUE TITLE
При дисконнекте игрока выбрасывается исключение

### ISSUE THREAD

**Issue by freepower311** [moevm/adfmp18-poker#64]
Проверялось на турнире №23
WebSocket recieve {"type": "disconnected", "id": 8}
Exception in thread "Thread-13" java.lang.RuntimeException: No OpenGL context found in the current thread.
Еще интересно, что при повторном заходе все проходило гладко.

**Comment by aaaaaa2493** [comment]
Ты знаешь что делать?

**Comment by freepower311** [comment]
Примерно, но если и сделаю, то только завтра

**Comment by aaaaaa2493** [comment]
Я пофиксил
